SELECT TOP 200 *

FROM "CLP123432"."ENERGIA_TOTAL" 
LEFT JOIN "CLP123432"."PLANILHAO_CLIENTE" ON ANLAGE = ZCGINSTAL

WHERE ("QUEDA" >= '4' AND "QUEDA" <= '24') 
AND ("LOCALIDADE" = 'RECIFE') 
AND ("ZCGBAIRR" IN ('BOA VIAGEM', 'GRACAS', 'ESPINHEIRO'))
AND ("ZCGSITUCC" = 'LIGADO')
--AND ("ZCGCLASSE" <> 'B')
AND (
   ( UPPER("ZCGDSCNAE") LIKE  UPPER('%PADARIA%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%RESTAURANTES%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%BARES%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%GELADOS%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%FRIGORÍFICO%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%AÇOUGUE%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%Atividades de condicionamento físico%'))
OR ( UPPER("ZCGDSCNAE") LIKE  UPPER('%Cabeleireiros%'))

OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%PADARIA%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%PANIFICA%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('% PAO %'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%RESTAURANTE%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%BARES%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('% BAR %'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%GELADO%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%SORVETE%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%FRIGORÍFICO%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%CARNES%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('% CARNE %'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%AÇOUGUE%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%Atividades de condicionamento físico%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%ACADEMIA%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%GYM%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%Cabeleireiro%'))
OR ( UPPER("ZCGNOMCLI") LIKE  UPPER('%Beleza%'))

)

ORDER BY "Energia_irr" DESC
