SELECT SETOR,UTD , 
LEFT(DATA_ENCE,7) REF,
CASE WHEN EQUIPE = 'CELPE' THEN 'BPROPRIO' ELSE 'BEPS'  END EQUIPE,
tpnota_geracao GERACAO ,

SUM(INPS) AS INPS_TT,
 SUM(TOI) AS TOI_TT, 
 SUM(F100) AS F100_TT, SUM(F200) AS F200_TT,  
 SUM(QTD_FAT) AS QTD_FAT_TT,
  SUM(QTD_CAN) AS QTD_CAN_TT,
   SUM(QTD_PEN) AS QTD_PEN_TT,
 CASE WHEN SUM(TOI) = 0 THEN 0 ELSE CAST(SUM(F100)/SUM(TOI) AS DECIMAL(10,4)) END AS F100_TOI_TT, 
CASE WHEN SUM(TOI) = 0 THEN 0 ELSE CAST(SUM(F200)/SUM(TOI) AS DECIMAL(10,4)) END AS F200_TOI_TT, 
CASE WHEN SUM(INPS) = 0 THEN 0 ELSE CAST(SUM(TOI)/SUM(INPS) AS DECIMAL(10,4)) END AS PROC_TT, 
CASE WHEN (SUM(CASE WHEN (USERCODE IN('VNRE','VREL')) THEN 1 ELSE 0 END)) = 0 THEN 0 ELSE (CAST(((SUM(VNRE))/(SUM(CASE WHEN (USERCODE IN('VNRE','VREL')) THEN 1 ELSE 0 END))) AS DECIMAL (10,4))) END AS IMPI_TT,
CAST((((SUM(CASE WHEN DADOS.STATUS IN ('AGUARDANDO_LAUDO','SEM_FATURAR') THEN 1 ELSE 0 END))*(CASE WHEN (SUM(TOI)) = 0 THEN 0 ELSE (CAST(SUM(CASE WHEN DADOS.CAUSA IS NOT NULL THEN KWH_RECUPERADO ELSE 0 END)/SUM(TOI)AS DECIMAL(10,2))) END)*(CASE WHEN (SUM(TOI)) = 0 THEN 0 ELSE (CAST((1-(SUM(CASE WHEN (DADOS.CAUSA < 299 AND DADOS.STATUS IN ('CANCELADO','SEM_COBRANCA')) THEN 1 ELSE 0 END))/(SUM(TOI))) AS DECIMAL(10,2)) ) END))/1000) AS DECIMAL(10,2)) AS ENERGIA_PROJ,
CAST((SUM(CASE WHEN DADOS.CAUSA IS NOT NULL THEN KWH_RECUPERADO ELSE 0 END)/1000) AS DECIMAL(10,2)) AS MWH_TT, 

CASE WHEN (SUM(TOI)) = 0 THEN 0 ELSE (CAST(SUM(CASE WHEN DADOS.CAUSA IS NOT NULL THEN KWH_RECUPERADO ELSE 0 END)/SUM(TOI)AS DECIMAL(10,2))) END  AS KWHTOI_TT, 
CASE WHEN SUM(CASE WHEN KWH_RECUPERADO > 0 THEN TOI ELSE 0 END)=0 THEN 0 ELSE (CAST(SUM(CASE WHEN DADOS.CAUSA IS NOT NULL THEN KWH_RECUPERADO ELSE 0 END)/SUM(CASE WHEN KWH_RECUPERADO > 0 THEN TOI ELSE 0 END)AS DECIMAL(10,2))) END  AS KWHTOIFAT_TT,

CASE WHEN (SUM(INPS)) = 0 THEN 0 ELSE (CAST(SUM(CASE WHEN DADOS.CAUSA IS NOT NULL THEN KWH_RECUPERADO ELSE 0 END)/(SUM(INPS))AS DECIMAL(10,2))) END AS KWHINSP_TT , 
CASE WHEN (SUM(TOI)) = 0 THEN 0 ELSE (CAST((1-(SUM(CASE WHEN (DADOS.CAUSA < 299 AND DADOS.STATUS IN ('CANCELADO','SEM_COBRANCA')) THEN 1 ELSE 0 END))/(SUM(TOI))) AS DECIMAL(10,4)) ) END AS EFET_TT,
CASE WHEN (SUM(CASE WHEN DADOS.STATUS IN ('FATURADO','CANCELADO','SEM_COBRANCA') THEN 1 ELSE 0 END)) = 0 THEN 0 ELSE (CAST((SUM(CASE WHEN (DADOS.CAUSA < 299 AND DADOS.STATUS IN ('FATURADO')) THEN 1 ELSE 0 END))/(SUM(CASE WHEN DADOS.STATUS IN ('FATURADO','CANCELADO','SEM_COBRANCA') THEN 1 ELSE 0 END)) AS DECIMAL(10,4))) END  AS EFET_SEMP_TT,
CASE WHEN (SUM(CASE WHEN (DADOS.CAUSA < 299 AND DADOS.STATUS NOT IN ('CANCELADO','SEM_COBRANCA')) THEN 1 ELSE 0 END)) = 0 THEN 0 ELSE (CAST(SUM(CASE WHEN DADOS.STATUS = 'FATURADO' THEN 1 ELSE 0 END)/SUM(CASE WHEN (DADOS.CAUSA < 299 AND DADOS.STATUS NOT IN ('CANCELADO','SEM_COBRANCA')) THEN 1 ELSE 0 END) AS DECIMAL(10,4)) ) END AS PERC_FAT_TT

-- TOTAIS - FINAIS

FROM (SELECT  * FROM "CLP123432"."PLANILHAO_NOTA_CI" WHERE LEFT(DATA_ENCE,4)= '2018' AND GRUPO = 'GRUPO_B_SEM_IP' AND tpnota_geracao IS NOT NULL ) AS DADOS

GROUP BY SETOR,UTD ,
 CASE WHEN EQUIPE = 'CELPE' THEN 'BPROPRIO' ELSE 'BEPS'  END,LEFT(DATA_ENCE,7) , tpnota_geracao
 ORDER BY SETOR , UTD;