SELECT count(*) FROM (
SELECT  top 10 c.ZCGINSTAL , DT_ULT_FAT, c."MES-01", c."MES-02", c."MES-03", o."MES-01", o."MES-02", o."MES-03",
zcgsitucc , utd, municipio, cli.localidade, zcgbairr , zcglatitu , zcglongit,CASE WHEN E."Energia_def" > 0 THEN E."Energia_def" ELSE 0 END KWH , M.*
  FROM "CLP123432"."PLANILHAO_CONSUMO" c
left join "CLP123432"."PLANILHAO_OCLE" o
on c.ZCGINSTAL = o.ZCGINSTAL
left join (select * from "CLP123432"."PLANILHAO_CLIENTE" where zcgsitucc <> 'BAIXADO') cli
  on cli.ZCGINSTAL = o.ZCGINSTAL
  LEFT JOIN "CLP124051"."ENERGIA_TOTAL" E 
  ON E.ANLAGE = c.ZCGINSTAL
  LEFT JOIN "CLP124051"."MOTOPROP" M
  ON M.INSTALACAO = C.ZCGINSTAL
WHERE c."MES-01" IN (30,100) and setor LIKE 'METROPOLITANO');




SELECT 
--utd , 
zcgsitucc , 
--OCLE,
CASE WHEN OCLE LIKE '0000' THEN 'LIDO NORMAL' WHEN OCLE LIKE '%0' THEN 'NAO LIDO' ELSE 'LIDO' END OCLE,
CASE 
	WHEN KWH > 300 THEN 'INSPECAO'
	WHEN ("ITENS DE VERIFICAÇÃO - RESPOSTA3" = 'LOCAL DO MEDIDOR INTERNO' AND "ITENS DE VERIFICAÇÃO - RESPOSTA4" <> 'APARTAMENTO') THEN 'EXTERNALIZAR'
	ELSE 'SUBSTITUIR' END ACAOOCLE,
RETORNO,
count(*) QTD,
SUM(CASE WHEN KWH < 5000 THEN 1 ELSE 0 END) F1,
SUM(CASE WHEN KWH BETWEEN 5000 AND 10000 THEN 1 ELSE 0 END) F2,
SUM(CASE WHEN KWH BETWEEN 10000 AND 25000 THEN 1 ELSE 0 END) F3,
SUM(CASE WHEN KWH > 25000 THEN 1 ELSE 0 END) F4


FROM (
SELECT   c.ZCGINSTAL , DT_ULT_FAT, c."MES-01", c."MES-02", c."MES-03", o."MES-01" OCLE, o."MES-02", o."MES-03",
zcgsitucc , utd, municipio, cli.localidade, zcgbairr , zcglatitu , zcglongit,CASE WHEN E."Energia_def" > 0 THEN E."Energia_def" ELSE 0 END KWH , M.*
  FROM "CLP123432"."PLANILHAO_CONSUMO" c
left join "CLP123432"."PLANILHAO_OCLE" o
on c.ZCGINSTAL = o.ZCGINSTAL
left join (select * from "CLP123432"."PLANILHAO_CLIENTE" where zcgsitucc <> 'BAIXADO') cli
  on cli.ZCGINSTAL = o.ZCGINSTAL
  LEFT JOIN "CLP124051"."ENERGIA_TOTAL" E 
  ON E.ANLAGE = c.ZCGINSTAL
  LEFT JOIN "CLP124051"."MOTOPROP" M
  ON LPAD(M.INSTALACAO,10,0) = C.ZCGINSTAL
WHERE c."MES-01" IN (30,100) and setor LIKE 'METROPOLITANO'  AND "RETORNO" LIKE '%150206-REGULARIZAR%' AND "DATA" >= '2018-09-15' ) 
GROUP BY --utd , 
zcgsitucc , 
CASE WHEN OCLE LIKE '0000' THEN 'LIDO NORMAL' WHEN OCLE LIKE '%0' THEN 'NAO LIDO' ELSE 'LIDO' END ,
CASE 
	WHEN KWH > 300 THEN 'INSPECAO'
	WHEN ("ITENS DE VERIFICAÇÃO - RESPOSTA3" = 'LOCAL DO MEDIDOR INTERNO' AND "ITENS DE VERIFICAÇÃO - RESPOSTA4" <> 'APARTAMENTO') THEN 'EXTERNALIZAR'
	ELSE 'SUBSTITUIR' END ,
RETORNO
ORDER BY ACAOOCLE;





SELECT   c.ZCGINSTAL , DT_ULT_FAT, c."MES-01", c."MES-02", c."MES-03", o."MES-01" OCLE, o."MES-02", o."MES-03",
zcgsitucc , utd, municipio, cli.localidade, zcgbairr , zcglatitu , zcglongit,CASE WHEN E."Energia_def" > 0 THEN E."Energia_def" ELSE 0 END KWH ,
CASE WHEN o."MES-01" LIKE '0000' THEN 'LIDO NORMAL' WHEN o."MES-01" LIKE '%0' THEN 'NAO LIDO' ELSE 'LIDO' END OCLE,
CASE 
	WHEN E."Energia_def" > 300 THEN 'INSPECAO'
	WHEN ("ITENS DE VERIFICAÇÃO - RESPOSTA3" = 'LOCAL DO MEDIDOR INTERNO' AND "ITENS DE VERIFICAÇÃO - RESPOSTA4" <> 'APARTAMENTO') THEN 'EXTERNALIZAR'
	ELSE 'SUBSTITUIR' END ACAOOCLE
	--, M.* 
  FROM "CLP123432"."PLANILHAO_CONSUMO" c
left join "CLP123432"."PLANILHAO_OCLE" o
on c.ZCGINSTAL = o.ZCGINSTAL
left join (select * from "CLP123432"."PLANILHAO_CLIENTE" where zcgsitucc <> 'BAIXADO') cli
  on cli.ZCGINSTAL = o.ZCGINSTAL
  LEFT JOIN "CLP124051"."ENERGIA_TOTAL" E 
  ON E.ANLAGE = c.ZCGINSTAL
  LEFT JOIN "CLP124051"."MOTOPROP" M
  ON LPAD(M.INSTALACAO,10,0) = C.ZCGINSTAL
  
WHERE c."MES-01" IN (30,100) and setor LIKE 'METROPOLITANO' AND "RETORNO" LIKE '%150206-REGULARIZAR%' AND "DATA" >= '2018-09-15'
