SELECT A.*,B.* ,"MES-01","MES-13" FROM 
(select * from  "CLP124529"."201707") A
RIGHT JOIN 
(select ZCGINSTAL , ZCGACCOUN, LEFT(ZCGTARTYP,1) GRUPO ,ZCGTARTYP ,
CASE WHEN ZCGTARTYP LIKE '%LV' THEN 'LIVRE' ELSE 'CATIVO' END TIPO, ZCGCLASSE 
from "CLP123432"."PLANILHAO_CLIENTE" WHERE ZCGCLASSE IN ('C','D')) B
ON A."Instalacao" = B.ZCGINSTAL
LEFT JOIN (SELECT * FROM "CLP123432"."PLANILHAO_CONSUMO") C
ON A."Instalacao" = C.ZCGINSTAL
WHERE  "Grupo" LIKE 'A'



SELECT A.*,B.* ,"MES-01","MES-13" FROM 
(select * from  "CLP124529"."201707") A
LEFT JOIN 
(select ZCGINSTAL , ZCGACCOUN, LEFT(ZCGTARTYP,1) GRUPO ,ZCGTARTYP ,
CASE WHEN ZCGTARTYP LIKE '%LV' THEN 'LIVRE' ELSE 'CATIVO' END TIPO, ZCGCLASSE 
from "CLP123432"."PLANILHAO_CLIENTE" WHERE ZCGCLASSE IN ('C','D')) B
ON A."Instalacao" = B.ZCGINSTAL
LEFT JOIN (SELECT * FROM "CLP123432"."PLANILHAO_CONSUMO") C
ON A."Instalacao" = C.ZCGINSTAL
WHERE  "Grupo" LIKE 'A'



SELECT TOP 10 ANLAGE,
SUM(CASE WHEN OPERAND LIKE '%MED%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) MED1 ,
SUM(CASE WHEN OPERAND LIKE '%MED%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) MED2 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) FAT1 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) FAT2 
FROM  
"NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_CONSUMOS"
WHERE DTREF IN ('201807','201707') AND ANLAGE = ('0006131439')
GROUP BY ANLAGE

---------------------------------------------------------------------

SELECT A.*,B.* ,C.* FROM 
(select * from  "CLP124529"."201707") A
RIGHT JOIN 
(select ZCGINSTAL , ZCGACCOUN, LEFT(ZCGTARTYP,1) GRUPO ,ZCGTARTYP ,
CASE WHEN ZCGTARTYP LIKE '%LV' THEN 'LIVRE' ELSE 'CATIVO' END TIPO, ZCGCLASSE 
from "CLP123432"."PLANILHAO_CLIENTE" WHERE ZCGCLASSE IN ('C','D')) B
ON A."Instalacao" = B.ZCGINSTAL
LEFT JOIN ( 
SELECT  ANLAGE,
SUM(CASE WHEN OPERAND LIKE '%MED%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) MED1 ,
SUM(CASE WHEN OPERAND LIKE '%MED%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) MED2 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) FAT1 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) FAT2 
FROM  
"NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_CONSUMOS"
WHERE DTREF IN ('201807','201707')

GROUP BY ANLAGE

) C
ON A."Instalacao" = C.ANLAGE
WHERE  "Grupo" LIKE 'A'

----------------------------------------------------------------------

SELECT A.*,B.* ,C.* FROM 
(select * from  "CLP124529"."TESTE1") A
LEFT JOIN 
(select ZCGINSTAL , ZCGACCOUN, LEFT(ZCGTARTYP,1) GRUPO ,ZCGTARTYP ,
CASE WHEN ZCGTARTYP LIKE '%LV' THEN 'LIVRE' ELSE 'CATIVO' END TIPO, ZCGCLASSE 
from "CLP123432"."PLANILHAO_CLIENTE" WHERE ZCGCLASSE IN ('C','D') AND ZCGSITUCC <>'BAIXADO' ) B
ON A."Instalacao" = B.ZCGINSTAL
LEFT JOIN ( 
SELECT  ANLAGE,
SUM(CASE WHEN OPERAND LIKE 'CA_MED_TT' AND DTREF = '201807' THEN WERT1 ELSE 0 END) MED1 ,
SUM(CASE WHEN OPERAND LIKE 'CA_MED_TT' AND DTREF = '201707' THEN WERT1 ELSE 0 END) MED2 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) FAT1 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) FAT2 
FROM  
"NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_CONSUMOS"
WHERE DTREF IN ('201807','201707')

GROUP BY ANLAGE

) C
ON A."Instalacao" = C.ANLAGE


-------------------------------------------------------
SELECT 
SUM(CASE WHEN TIPO = 'LIVRE' THEN MED1 ELSE FAT1 END ) AS MED11,
SUM(CASE WHEN TIPO = 'LIVRE' THEN MED2 ELSE FAT2 END ) AS MED22,
SUM(MED1),SUM(MED2)
FROM (SELECT A.*,B.* ,C.* FROM 
(select * from  "CLP124529"."TESTE1") A
LEFT JOIN 
(select ZCGINSTAL , ZCGACCOUN, LEFT(ZCGTARTYP,1) GRUPO ,ZCGTARTYP ,
CASE WHEN ZCGTARTYP LIKE '%LV' THEN 'LIVRE' ELSE 'CATIVO' END TIPO, ZCGCLASSE 
from "CLP123432"."PLANILHAO_CLIENTE" WHERE ZCGCLASSE IN ('C','D') AND ZCGSITUCC <>'BAIXADO' ) B
ON A."Instalacao" = B.ZCGINSTAL
LEFT JOIN ( 
SELECT  ANLAGE,
SUM(CASE WHEN OPERAND LIKE 'CA_MED_TT' AND DTREF = '201807' THEN WERT1 ELSE 0 END) MED1 ,
SUM(CASE WHEN OPERAND LIKE 'CA_MED_TT' AND DTREF = '201707' THEN WERT1 ELSE 0 END) MED2 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201807' THEN WERT1 ELSE 0 END) FAT1 ,
SUM(CASE WHEN OPERAND LIKE '%FAT%' AND DTREF = '201707' THEN WERT1 ELSE 0 END) FAT2 
FROM  
"NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_CONSUMOS"
WHERE DTREF IN ('201807','201707')

GROUP BY ANLAGE

) C
ON A."Instalacao" = C.ANLAGE)

---------------------------------------------------------------------------------------

SELECT * FROM   
"NEO_COR"."neo.cor.data::MODEL.TABLES.ZCT_DS_CONSUMOS"
WHERE ANLAGE  = 0003199817
 ORDER BY DTREF
 
 
 
 select COUNT (*) from  "CLP124529"."TESTE1"