select 
f.TEMPOf,
f.Energiaf/f.Qtd_fatf as kWh_FAT,
CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END as ITOI,
CAST( (f.Energiaf/f.Qtd_fatf)*(CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END) AS DECIMAL(10,2)) AS PREV
from (
select 
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 140 THEN '14. < 140'
ELSE '15. > 140' END TEMPOf,

sum (kwh_recuperado) as Energiaf,
count (nota) as Qtd_fatf
from "CLP124051"."PLANILHAO_NOTA_CI"
where ERDAT >= '2019-01-01'
group by 
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 140 THEN '14. < 140'
ELSE '15. > 140' END 
) as f
Left join
(
select CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 140 THEN '14. < 140'
ELSE '15. > 140' END TEMPOc,
count (nota) as Qtd_cancc
from "CLP124051"."PLANILHAO_NOTA_CI"
where DT_CONCLUS >= '2019-01-01'
and status = 'CANCELADO'
group by 
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 140 THEN '14. < 140'
ELSE '15. > 140' END 
) as c
on f.TEMPOf = c.TEMPOc

ORDER BY f.TEMPOf

;


select 
f.TEMPOf,
f.Energiaf/f.Qtd_fatf as kWh_FAT,
CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 0 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END as ITOI,
CAST( (f.Energiaf/f.Qtd_fatf)*(CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 0 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END) AS DECIMAL(10,2)) AS PREV
from (
select DAYS_BETWEEN (DATA_ENCE , ERDAT)  TEMPOf,

sum (kwh_recuperado) as Energiaf,
count (nota) as Qtd_fatf
from "CLP124051"."PLANILHAO_NOTA_CI"
where ERDAT >= '2019-01-01'
group by 
DAYS_BETWEEN (DATA_ENCE , ERDAT) 
) as f
Left join
(
select  DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) TEMPOc,
count (nota) as Qtd_cancc
from "CLP124051"."PLANILHAO_NOTA_CI"
where DT_CONCLUS >= '2019-01-01'
and status = 'CANCELADO'
group by 
DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) 
) as c
on f.TEMPOf = c.TEMPOc

ORDER BY f.TEMPOf

;

select 
f.TEMPOf,
f.UTDf,
f.Energiaf/f.Qtd_fatf as kWh_FAT,
CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END as ITOI,
CAST( (f.Energiaf/f.Qtd_fatf)*(CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END) AS DECIMAL(10,2)) AS PREV
from (
select UTD UTDf,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 140 THEN '14. < 140'
ELSE '15. > 140' END TEMPOf,

sum (kwh_recuperado) as Energiaf,
count (nota) as Qtd_fatf
from "CLP124051"."PLANILHAO_NOTA_CI"
where ERDAT >= '2019-01-01'
group by UTD,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 140 THEN '14. < 140'
ELSE '15. > 140' END 
) as f
Left join
(
select UTD UTDc,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 140 THEN '14. < 140'
ELSE '15. > 140' END TEMPOc,
count (nota) as Qtd_cancc
from "CLP124051"."PLANILHAO_NOTA_CI"
where DT_CONCLUS >= '2019-01-01'
and status = 'CANCELADO'
group by UTD,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 10 THEN '01. < 10'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 20 THEN '02. < 20'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '03. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 40 THEN '04. < 40'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 50 THEN '05. < 50'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '06. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 70 THEN '07. < 70'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 80 THEN '08. < 80'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '09. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 100 THEN '10. < 100'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 110 THEN '11. < 110'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '12. < 120'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 130 THEN '13. < 130'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 140 THEN '14. < 140'
ELSE '15. > 140' END 
) as c
on f.TEMPOf = c.TEMPOc AND f.UTDf = c.UTDc

ORDER BY f.UTDf, f.TEMPOf

;

select 
f.TEMPOf,
f.UTDf,
f.Energiaf/f.Qtd_fatf as kWh_FAT,
CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END as ITOI,
CAST( (f.Energiaf/f.Qtd_fatf)*(CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END) AS DECIMAL(10,2)) AS PREV
from (
select UTD UTDf,
CASE
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '04. < 120'
ELSE '05. > 120' END TEMPOf,

sum (kwh_recuperado) as Energiaf,
count (nota) as Qtd_fatf
from "CLP124051"."PLANILHAO_NOTA_CI"
where ERDAT >= '2019-01-01'
group by UTD,
CASE
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '04. < 120'
ELSE '05. > 120' END
) as f
Left join
(
select UTD UTDc,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '04. < 120'
ELSE '05. > 120' END TEMPOc,
count (nota) as Qtd_cancc
from "CLP124051"."PLANILHAO_NOTA_CI"
where DT_CONCLUS >= '2019-01-01' and 
status = 'CANCELADO'
group by UTD,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '04. < 120'
ELSE '05. > 120' END
) as c
on f.TEMPOf = c.TEMPOc AND f.UTDf = c.UTDc

ORDER BY f.UTDf, f.TEMPOf

;


select 
f.TEMPOf,
f.UTDf,
f.Energiaf/f.Qtd_fatf as kWh_FAT,
CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END as ITOI,
CAST( (f.Energiaf/f.Qtd_fatf)*(CASE WHEN f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) IS NULL THEN 1 ELSE f.Qtd_fatf/(f.Qtd_fatf+c.Qtd_cancc) END) AS DECIMAL(10,2)) AS PREV
from (
select UTD UTDf,
CASE
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '04. < 120'
ELSE '05. > 120' END TEMPOf,

sum (kwh_recuperado) as Energiaf,
count (nota) as Qtd_fatf
from "CLP124051"."PLANILHAO_NOTA_CI"
--where ERDAT >= '2019-01-01'
group by UTD,
CASE
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , ERDAT) < 120 THEN '04. < 120'
ELSE '05. > 120' END
) as f
Left join
(
select UTD UTDc,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '04. < 120'
ELSE '05. > 120' END TEMPOc,
count (nota) as Qtd_cancc
from "CLP124051"."PLANILHAO_NOTA_CI"
where --DT_CONCLUS >= '2019-01-01' and 
status = 'CANCELADO'
group by UTD,
CASE 
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 30 THEN '01. < 30'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 60 THEN '02. < 60'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 90 THEN '03. < 90'
WHEN DAYS_BETWEEN (DATA_ENCE , DT_CONCLUS) < 120 THEN '04. < 120'
ELSE '05. > 120' END
) as c
on f.TEMPOf = c.TEMPOc AND f.UTDf = c.UTDc

ORDER BY f.UTDf, f.TEMPOf