SELECT *
FROM "CLP124051"."PLANILHAO_NOTA_CI" 
WHERE ("DATA_ENCE" = '1900-01-01' AND "GRUPO" IN ('GRUPO_B_SEM_IP', 'IP_MEDIDA') AND "SETOR" = 'METROPOLITANO' AND "CT" <> '1PE000' AND "EQUIPE" = 'CELPE' AND "GERACAO" = 'NS')
